 build:
    runs-on: ubuntu-18.04
    steps:
    - name: Cleanup Space
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - uses: rokibhasansagar/slimhub_actions@main
    - run: source ubuntu-run.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
0 comments on commit 115d2c0
